WIP :Validating submissions
ufcg-lsd/asperathos-visualizer pull request #19
Opened 2019-04-08 19:51 UTC by joseims

Tests are missing

2019-04-10 18:48 UTC, joseims commented
Everything that the k8s-grafana plugin uses is either not fixed or validated elsewhere

2019-04-11 17:23 UTC, clenimar requested changes
is this still a WIP? title, description and the set of modifications are confusing.

2019-04-11 17:23 UTC, clenimar commented on visualizer/plugins/k8s_grafana/plugin.py
> -
please keep these blank lines.

2019-04-11 17:51 UTC, joseims commented
After analyzing the code i found out that no validation is necessary since all the variables used by the k8s-grafana are either not fixed or validated elsewhere. So i just reused the pull request to rename the file visualizer/tests/unit/plugins/test_buider.py to  visualizer/tests/unit/plugins/test_builder.py

2019-04-15 18:02 UTC, matheuscmelo requested changes
Could you please squash these commits? Seems to be a lot of them for just too little modifications. Besides, LGTM.

2019-04-17 00:17 UTC, clenimar commented
agreed. you've got way more commits than needed. try to keep things simple. one change per commit, and a (really small) highly-related set of commits per PR. also improve the title and description to reflect better what you're proposing.

suggested rewording: 
fix typo in filename (buider->builder); conform import to pep8

cheers.

2019-04-17 14:27 UTC, matheuscmelo approved these changes

2019-04-17 14:29 UTC, clenimar approved these changes

2019-04-17 14:30 UTC, merged